server:
  port: 8081
spring:
  application:
    name: api_1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:    instance-id: ${spring.application.name}:${random.int}
get_product_by_id:
  url: http://api_2/api2/search/{productId}
post_add_product:
  url: http://api_2/api2/add
post_update_product:
  url: http://api_2/api2/update
get_delete_product:
  url: http://api_2/api2/delete/{productId}